# Generated by Django 5.2.7 on 2025-10-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.IntegerField(blank=True, max_length=40, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Cover_img', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
        ),
    ]
