# Generated by Django 5.2.7 on 2025-11-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.IntegerField(blank=True, max_length=40, null=True)),
                ('Author', models.IntegerField(blank=True, max_length=40, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Cover_pic', models.ImageField(blank=True, null=True, upload_to='books')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
