# Generated by Django 5.2.7 on 2025-11-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_bookdb_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='Category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookdb',
            name='Price',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bookdb',
            name='Publisher',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='Author',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='Book_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
