# Generated by Django 5.2.7 on 2025-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_bookdb_category_bookdb_price_bookdb_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
