# Generated by Django 5.2.7 on 2025-11-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_alter_bookdb_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdb',
            old_name='Category',
            new_name='Category_name',
        ),
    ]
