# Generated by Django 5.2.7 on 2025-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=40, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Subject', models.CharField(blank=True, max_length=40, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
