# Generated by Django 5.2.7 on 2025-11-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=40, null=True)),
                ('Password', models.CharField(blank=True, max_length=40, null=True)),
                ('Conf_password', models.CharField(blank=True, max_length=40, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
