# Generated by Django 5.2.7 on 2025-12-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_registerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=40, null=True)),
                ('Book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Total_price', models.IntegerField(blank=True, null=True)),
                ('Book_img', models.ImageField(blank=True, null=True, upload_to='Cart')),
            ],
        ),
    ]
